/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Asset,
    AssetFromJSON,
    AssetToJSON,
    AssetOrder,
    AssetOrderFromJSON,
    AssetOrderToJSON,
    AssetSortBy,
    AssetSortByFromJSON,
    AssetSortByToJSON,
    AssetStatus,
    AssetStatusFromJSON,
    AssetStatusToJSON,
    AssetTags,
    AssetTagsFromJSON,
    AssetTagsToJSON,
    AssetType,
    AssetTypeFromJSON,
    AssetTypeToJSON,
    SortOrder,
    SortOrderFromJSON,
    SortOrderToJSON,
} from '../models';

export interface AssetsAssetIdPutRequest {
    assetId: number;
    asset?: Asset;
}

export interface AssetsAssetIdTagsDeleteRequest {
    assetId: number;
}

export interface AssetsAssetIdTagsPostRequest {
    assetId: number;
    assetTags?: AssetTags;
}

export interface AssetsAssetIdTagsPutRequest {
    assetId: number;
    assetTags?: AssetTags;
}

export interface AssetsCheckoutPostRequest {
    assetOrder?: AssetOrder;
}

export interface AssetsGetRequest {
    resellerCustomerId?: number;
    publisherId?: number;
    externalOrderId?: string | null;
    externalOrderIds?: Array<string> | null;
    reservationId?: string | null;
    assetType?: AssetType;
    status?: AssetStatus;
    page?: number;
    pageSize?: number;
    search?: string | null;
    sortBy?: AssetSortBy;
    sortOrder?: SortOrder;
}

export interface AssetsIdGetRequest {
    id: number;
}

export interface AssetsOrdersGetRequest {
    resellerCustomerId?: number;
    publisherId?: number;
    externalOrderId?: string | null;
    externalOrderIds?: Array<string> | null;
    reservationId?: string | null;
    assetType?: AssetType;
    status?: AssetStatus;
    page?: number;
    pageSize?: number;
    search?: string | null;
    sortBy?: AssetSortBy;
    sortOrder?: SortOrder;
}

export interface AssetsVerifyPostRequest {
    assetOrder?: AssetOrder;
}

/**
 * 
 */
export class AssetsApi extends runtime.BaseAPI {

    /**
     */
    async assetsAssetIdPutRaw(requestParameters: AssetsAssetIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assetId === null || requestParameters.assetId === undefined) {
            throw new runtime.RequiredError('assetId','Required parameter requestParameters.assetId was null or undefined when calling assetsAssetIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/{assetId}`.replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters.assetId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AssetToJSON(requestParameters.asset),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assetsAssetIdPut(requestParameters: AssetsAssetIdPutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.assetsAssetIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async assetsAssetIdTagsDeleteRaw(requestParameters: AssetsAssetIdTagsDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assetId === null || requestParameters.assetId === undefined) {
            throw new runtime.RequiredError('assetId','Required parameter requestParameters.assetId was null or undefined when calling assetsAssetIdTagsDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/{assetId}/tags`.replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters.assetId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assetsAssetIdTagsDelete(requestParameters: AssetsAssetIdTagsDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.assetsAssetIdTagsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async assetsAssetIdTagsPostRaw(requestParameters: AssetsAssetIdTagsPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assetId === null || requestParameters.assetId === undefined) {
            throw new runtime.RequiredError('assetId','Required parameter requestParameters.assetId was null or undefined when calling assetsAssetIdTagsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/{assetId}/tags`.replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters.assetId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssetTagsToJSON(requestParameters.assetTags),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assetsAssetIdTagsPost(requestParameters: AssetsAssetIdTagsPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.assetsAssetIdTagsPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async assetsAssetIdTagsPutRaw(requestParameters: AssetsAssetIdTagsPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assetId === null || requestParameters.assetId === undefined) {
            throw new runtime.RequiredError('assetId','Required parameter requestParameters.assetId was null or undefined when calling assetsAssetIdTagsPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/{assetId}/tags`.replace(`{${"assetId"}}`, encodeURIComponent(String(requestParameters.assetId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AssetTagsToJSON(requestParameters.assetTags),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assetsAssetIdTagsPut(requestParameters: AssetsAssetIdTagsPutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.assetsAssetIdTagsPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async assetsCheckoutPostRaw(requestParameters: AssetsCheckoutPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/checkout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssetOrderToJSON(requestParameters.assetOrder),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async assetsCheckoutPost(requestParameters: AssetsCheckoutPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.assetsCheckoutPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async assetsGetRaw(requestParameters: AssetsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Asset>>> {
        const queryParameters: any = {};

        if (requestParameters.resellerCustomerId !== undefined) {
            queryParameters['ResellerCustomerId'] = requestParameters.resellerCustomerId;
        }

        if (requestParameters.publisherId !== undefined) {
            queryParameters['PublisherId'] = requestParameters.publisherId;
        }

        if (requestParameters.externalOrderId !== undefined) {
            queryParameters['ExternalOrderId'] = requestParameters.externalOrderId;
        }

        if (requestParameters.externalOrderIds) {
            queryParameters['ExternalOrderIds'] = requestParameters.externalOrderIds;
        }

        if (requestParameters.reservationId !== undefined) {
            queryParameters['ReservationId'] = requestParameters.reservationId;
        }

        if (requestParameters.assetType !== undefined) {
            queryParameters['AssetType'] = requestParameters.assetType;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['Status'] = requestParameters.status;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['SortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['SortOrder'] = requestParameters.sortOrder;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssetFromJSON));
    }

    /**
     */
    async assetsGet(requestParameters: AssetsGetRequest, initOverrides?: RequestInit): Promise<Array<Asset>> {
        const response = await this.assetsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async assetsIdGetRaw(requestParameters: AssetsIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Asset>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling assetsIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetFromJSON(jsonValue));
    }

    /**
     */
    async assetsIdGet(requestParameters: AssetsIdGetRequest, initOverrides?: RequestInit): Promise<Asset> {
        const response = await this.assetsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async assetsOrdersGetRaw(requestParameters: AssetsOrdersGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<AssetOrder>>> {
        const queryParameters: any = {};

        if (requestParameters.resellerCustomerId !== undefined) {
            queryParameters['ResellerCustomerId'] = requestParameters.resellerCustomerId;
        }

        if (requestParameters.publisherId !== undefined) {
            queryParameters['PublisherId'] = requestParameters.publisherId;
        }

        if (requestParameters.externalOrderId !== undefined) {
            queryParameters['ExternalOrderId'] = requestParameters.externalOrderId;
        }

        if (requestParameters.externalOrderIds) {
            queryParameters['ExternalOrderIds'] = requestParameters.externalOrderIds;
        }

        if (requestParameters.reservationId !== undefined) {
            queryParameters['ReservationId'] = requestParameters.reservationId;
        }

        if (requestParameters.assetType !== undefined) {
            queryParameters['AssetType'] = requestParameters.assetType;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['Status'] = requestParameters.status;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.sortBy !== undefined) {
            queryParameters['SortBy'] = requestParameters.sortBy;
        }

        if (requestParameters.sortOrder !== undefined) {
            queryParameters['SortOrder'] = requestParameters.sortOrder;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AssetOrderFromJSON));
    }

    /**
     */
    async assetsOrdersGet(requestParameters: AssetsOrdersGetRequest, initOverrides?: RequestInit): Promise<Array<AssetOrder>> {
        const response = await this.assetsOrdersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async assetsVerifyPostRaw(requestParameters: AssetsVerifyPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AssetOrder>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/Assets/verify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssetOrderToJSON(requestParameters.assetOrder),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetOrderFromJSON(jsonValue));
    }

    /**
     */
    async assetsVerifyPost(requestParameters: AssetsVerifyPostRequest, initOverrides?: RequestInit): Promise<AssetOrder> {
        const response = await this.assetsVerifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
