/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AzurePlan,
    AzurePlanFromJSON,
    AzurePlanToJSON,
    AzureSubscription,
    AzureSubscriptionFromJSON,
    AzureSubscriptionToJSON,
    AzureSubscriptionAssignAdmin,
    AzureSubscriptionAssignAdminFromJSON,
    AzureSubscriptionAssignAdminToJSON,
    AzureSubscriptionRename,
    AzureSubscriptionRenameFromJSON,
    AzureSubscriptionRenameToJSON,
    AzureSubscriptionUpdated,
    AzureSubscriptionUpdatedFromJSON,
    AzureSubscriptionUpdatedToJSON,
    CreateAzureSubscriptionRequest,
    CreateAzureSubscriptionRequestFromJSON,
    CreateAzureSubscriptionRequestToJSON,
    PutAzureSubscription,
    PutAzureSubscriptionFromJSON,
    PutAzureSubscriptionToJSON,
} from '../models';

export interface AzurePlansAzurePlanIdAzureSubscriptionsGetRequest {
    azurePlanId: number;
    search?: string | null;
    page?: number;
    pageSize?: number;
}

export interface AzurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPutRequest {
    azurePlanId: number;
    id: number;
    azureSubscriptionAssignAdmin?: AzureSubscriptionAssignAdmin;
}

export interface AzurePlansAzurePlanIdAzureSubscriptionsIdCancelPostRequest {
    azurePlanId: number;
    id: number;
}

export interface AzurePlansAzurePlanIdAzureSubscriptionsIdEnablePostRequest {
    azurePlanId: number;
    id: number;
}

export interface AzurePlansAzurePlanIdAzureSubscriptionsIdGetRequest {
    azurePlanId: number;
    id: number;
}

export interface AzurePlansAzurePlanIdAzureSubscriptionsIdPutRequest {
    azurePlanId: number;
    id: number;
    putAzureSubscription?: PutAzureSubscription;
}

export interface AzurePlansAzurePlanIdAzureSubscriptionsIdRenamePatchRequest {
    azurePlanId: number;
    id: number;
    azureSubscriptionRename?: AzureSubscriptionRename;
}

export interface AzurePlansAzurePlanIdAzureSubscriptionsPostRequest {
    azurePlanId: number;
    createAzureSubscriptionRequest?: CreateAzureSubscriptionRequest;
}

export interface AzurePlansAzurePlanIdGetRequest {
    azurePlanId: number;
}

/**
 * 
 */
export class AzurePlansApi extends runtime.BaseAPI {

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsGetRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<AzureSubscription>>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AzureSubscriptionFromJSON));
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsGet(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsGetRequest, initOverrides?: RequestInit): Promise<Array<AzureSubscription>> {
        const response = await this.azurePlansAzurePlanIdAzureSubscriptionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPutRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPut.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions/{id}/assign-unique-admin`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AzureSubscriptionAssignAdminToJSON(requestParameters.azureSubscriptionAssignAdmin),
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPut(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPutRequest, initOverrides?: RequestInit): Promise<boolean> {
        const response = await this.azurePlansAzurePlanIdAzureSubscriptionsIdAssignUniqueAdminPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdCancelPostRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdCancelPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AzureSubscriptionUpdated>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdCancelPost.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdCancelPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions/{id}/cancel`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AzureSubscriptionUpdatedFromJSON(jsonValue));
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdCancelPost(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdCancelPostRequest, initOverrides?: RequestInit): Promise<AzureSubscriptionUpdated> {
        const response = await this.azurePlansAzurePlanIdAzureSubscriptionsIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdEnablePostRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdEnablePostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AzureSubscriptionUpdated>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdEnablePost.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdEnablePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions/{id}/enable`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AzureSubscriptionUpdatedFromJSON(jsonValue));
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdEnablePost(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdEnablePostRequest, initOverrides?: RequestInit): Promise<AzureSubscriptionUpdated> {
        const response = await this.azurePlansAzurePlanIdAzureSubscriptionsIdEnablePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdGetRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AzureSubscription>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdGet.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions/{id}`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AzureSubscriptionFromJSON(jsonValue));
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdGet(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdGetRequest, initOverrides?: RequestInit): Promise<AzureSubscription> {
        const response = await this.azurePlansAzurePlanIdAzureSubscriptionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdPutRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AzureSubscription>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdPut.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions/{id}`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PutAzureSubscriptionToJSON(requestParameters.putAzureSubscription),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AzureSubscriptionFromJSON(jsonValue));
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdPut(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdPutRequest, initOverrides?: RequestInit): Promise<AzureSubscription> {
        const response = await this.azurePlansAzurePlanIdAzureSubscriptionsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdRenamePatchRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdRenamePatchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AzureSubscriptionUpdated>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdRenamePatch.');
        }

        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsIdRenamePatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions/{id}/rename`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AzureSubscriptionRenameToJSON(requestParameters.azureSubscriptionRename),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AzureSubscriptionUpdatedFromJSON(jsonValue));
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsIdRenamePatch(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsIdRenamePatchRequest, initOverrides?: RequestInit): Promise<AzureSubscriptionUpdated> {
        const response = await this.azurePlansAzurePlanIdAzureSubscriptionsIdRenamePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsPostRaw(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdAzureSubscriptionsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}/azureSubscriptions`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAzureSubscriptionRequestToJSON(requestParameters.createAzureSubscriptionRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async azurePlansAzurePlanIdAzureSubscriptionsPost(requestParameters: AzurePlansAzurePlanIdAzureSubscriptionsPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.azurePlansAzurePlanIdAzureSubscriptionsPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async azurePlansAzurePlanIdGetRaw(requestParameters: AzurePlansAzurePlanIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AzurePlan>> {
        if (requestParameters.azurePlanId === null || requestParameters.azurePlanId === undefined) {
            throw new runtime.RequiredError('azurePlanId','Required parameter requestParameters.azurePlanId was null or undefined when calling azurePlansAzurePlanIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/AzurePlans/{azurePlanId}`.replace(`{${"azurePlanId"}}`, encodeURIComponent(String(requestParameters.azurePlanId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AzurePlanFromJSON(jsonValue));
    }

    /**
     */
    async azurePlansAzurePlanIdGet(requestParameters: AzurePlansAzurePlanIdGetRequest, initOverrides?: RequestInit): Promise<AzurePlan> {
        const response = await this.azurePlansAzurePlanIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
