/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BillingCycle,
    BillingCycleFromJSON,
    BillingCycleToJSON,
} from '../models';

export interface BillingCyclesGetRequest {
    includeUnknown?: boolean;
}

export interface BillingCyclesProductVariantProductVariantIdGetRequest {
    productVariantId: number;
}

/**
 * 
 */
export class BillingCyclesApi extends runtime.BaseAPI {

    /**
     */
    async billingCyclesCspNameDictionaryGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/BillingCycles/cspNameDictionary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async billingCyclesCspNameDictionaryGet(initOverrides?: RequestInit): Promise<{ [key: string]: string; }> {
        const response = await this.billingCyclesCspNameDictionaryGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async billingCyclesGetRaw(requestParameters: BillingCyclesGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<BillingCycle>>> {
        const queryParameters: any = {};

        if (requestParameters.includeUnknown !== undefined) {
            queryParameters['includeUnknown'] = requestParameters.includeUnknown;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/BillingCycles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BillingCycleFromJSON));
    }

    /**
     */
    async billingCyclesGet(requestParameters: BillingCyclesGetRequest, initOverrides?: RequestInit): Promise<Array<BillingCycle>> {
        const response = await this.billingCyclesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async billingCyclesProductVariantProductVariantIdGetRaw(requestParameters: BillingCyclesProductVariantProductVariantIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<BillingCycle>>> {
        if (requestParameters.productVariantId === null || requestParameters.productVariantId === undefined) {
            throw new runtime.RequiredError('productVariantId','Required parameter requestParameters.productVariantId was null or undefined when calling billingCyclesProductVariantProductVariantIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/BillingCycles/productVariant/{productVariantId}`.replace(`{${"productVariantId"}}`, encodeURIComponent(String(requestParameters.productVariantId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BillingCycleFromJSON));
    }

    /**
     */
    async billingCyclesProductVariantProductVariantIdGet(requestParameters: BillingCyclesProductVariantProductVariantIdGetRequest, initOverrides?: RequestInit): Promise<Array<BillingCycle>> {
        const response = await this.billingCyclesProductVariantProductVariantIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
