/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BlogItem,
    BlogItemFromJSON,
    BlogItemToJSON,
} from '../models';

export interface ApiV1BlogItemsGetRequest {
    count?: number;
    organizationId?: number;
}

/**
 * 
 */
export class BlogItemsApi extends runtime.BaseAPI {

    /**
     */
    async apiV1BlogItemsGetRaw(requestParameters: ApiV1BlogItemsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<BlogItem>>> {
        const queryParameters: any = {};

        if (requestParameters.count !== undefined) {
            queryParameters['count'] = requestParameters.count;
        }

        if (requestParameters.organizationId !== undefined) {
            queryParameters['organizationId'] = requestParameters.organizationId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/BlogItems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BlogItemFromJSON));
    }

    /**
     */
    async apiV1BlogItemsGet(requestParameters: ApiV1BlogItemsGetRequest, initOverrides?: RequestInit): Promise<Array<BlogItem>> {
        const response = await this.apiV1BlogItemsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
