/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AgreementTypeConsent,
    AgreementTypeConsentFromJSON,
    AgreementTypeConsentToJSON,
    ServiceAccountAgreement,
    ServiceAccountAgreementFromJSON,
    ServiceAccountAgreementToJSON,
} from '../models';

export interface ApiV1CustomertenantsCustomerTenantIdAgreementsGetRequest {
    customerTenantId: number;
    agreementTypeConsent?: AgreementTypeConsent;
}

export interface ApiV1CustomertenantsCustomerTenantIdAgreementsPostRequest {
    customerTenantId: number;
    serviceAccountAgreement?: ServiceAccountAgreement;
}

/**
 * 
 */
export class CustomerTenantAgreementsApi extends runtime.BaseAPI {

    /**
     */
    async apiV1CustomertenantsCustomerTenantIdAgreementsGetRaw(requestParameters: ApiV1CustomertenantsCustomerTenantIdAgreementsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ServiceAccountAgreement>>> {
        if (requestParameters.customerTenantId === null || requestParameters.customerTenantId === undefined) {
            throw new runtime.RequiredError('customerTenantId','Required parameter requestParameters.customerTenantId was null or undefined when calling apiV1CustomertenantsCustomerTenantIdAgreementsGet.');
        }

        const queryParameters: any = {};

        if (requestParameters.agreementTypeConsent !== undefined) {
            queryParameters['AgreementTypeConsent'] = requestParameters.agreementTypeConsent;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/customertenants/{customerTenantId}/agreements`.replace(`{${"customerTenantId"}}`, encodeURIComponent(String(requestParameters.customerTenantId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceAccountAgreementFromJSON));
    }

    /**
     */
    async apiV1CustomertenantsCustomerTenantIdAgreementsGet(requestParameters: ApiV1CustomertenantsCustomerTenantIdAgreementsGetRequest, initOverrides?: RequestInit): Promise<Array<ServiceAccountAgreement>> {
        const response = await this.apiV1CustomertenantsCustomerTenantIdAgreementsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1CustomertenantsCustomerTenantIdAgreementsPostRaw(requestParameters: ApiV1CustomertenantsCustomerTenantIdAgreementsPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ServiceAccountAgreement>> {
        if (requestParameters.customerTenantId === null || requestParameters.customerTenantId === undefined) {
            throw new runtime.RequiredError('customerTenantId','Required parameter requestParameters.customerTenantId was null or undefined when calling apiV1CustomertenantsCustomerTenantIdAgreementsPost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/customertenants/{customerTenantId}/agreements`.replace(`{${"customerTenantId"}}`, encodeURIComponent(String(requestParameters.customerTenantId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceAccountAgreementToJSON(requestParameters.serviceAccountAgreement),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceAccountAgreementFromJSON(jsonValue));
    }

    /**
     */
    async apiV1CustomertenantsCustomerTenantIdAgreementsPost(requestParameters: ApiV1CustomertenantsCustomerTenantIdAgreementsPostRequest, initOverrides?: RequestInit): Promise<ServiceAccountAgreement> {
        const response = await this.apiV1CustomertenantsCustomerTenantIdAgreementsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
