/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AzurePlan,
    AzurePlanFromJSON,
    AzurePlanToJSON,
    CustomerTenant,
    CustomerTenantFromJSON,
    CustomerTenantToJSON,
    CustomerTenantDetailed,
    CustomerTenantDetailedFromJSON,
    CustomerTenantDetailedToJSON,
    CustomerTenantType,
    CustomerTenantTypeFromJSON,
    CustomerTenantTypeToJSON,
} from '../models';

export interface CustomerTenantsCustomerTenantIdAzurePlanGetRequest {
    customerTenantId: number;
}

export interface CustomerTenantsExistingPostRequest {
    syncFromPublisher?: boolean;
    customerTenantDetailed?: CustomerTenantDetailed;
}

export interface CustomerTenantsGetRequest {
    organizationId?: number;
    publisherId?: number;
    programId?: number;
    consumerId?: number;
    domain?: string | null;
    domainPrefix?: string | null;
    customerTenantType?: CustomerTenantType;
    invoiceProfileId?: number;
    page?: number;
    pageSize?: number;
    search?: string | null;
}

export interface CustomerTenantsIdDeleteRequest {
    id: number;
}

export interface CustomerTenantsIdDetailedGetRequest {
    id: number;
}

export interface CustomerTenantsIdGetRequest {
    id: number;
}

export interface CustomerTenantsIdPutRequest {
    id: number;
    customerTenantDetailed?: CustomerTenantDetailed;
}

export interface CustomerTenantsPostRequest {
    customerTenantDetailed?: CustomerTenantDetailed;
}

/**
 * 
 */
export class CustomerTenantsApi extends runtime.BaseAPI {

    /**
     */
    async customerTenantsCustomerTenantIdAzurePlanGetRaw(requestParameters: CustomerTenantsCustomerTenantIdAzurePlanGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<AzurePlan>> {
        if (requestParameters.customerTenantId === null || requestParameters.customerTenantId === undefined) {
            throw new runtime.RequiredError('customerTenantId','Required parameter requestParameters.customerTenantId was null or undefined when calling customerTenantsCustomerTenantIdAzurePlanGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants/{customerTenantId}/azurePlan`.replace(`{${"customerTenantId"}}`, encodeURIComponent(String(requestParameters.customerTenantId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AzurePlanFromJSON(jsonValue));
    }

    /**
     */
    async customerTenantsCustomerTenantIdAzurePlanGet(requestParameters: CustomerTenantsCustomerTenantIdAzurePlanGetRequest, initOverrides?: RequestInit): Promise<AzurePlan> {
        const response = await this.customerTenantsCustomerTenantIdAzurePlanGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerTenantsExistingPostRaw(requestParameters: CustomerTenantsExistingPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomerTenantDetailed>> {
        const queryParameters: any = {};

        if (requestParameters.syncFromPublisher !== undefined) {
            queryParameters['syncFromPublisher'] = requestParameters.syncFromPublisher;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants/existing`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerTenantDetailedToJSON(requestParameters.customerTenantDetailed),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerTenantDetailedFromJSON(jsonValue));
    }

    /**
     */
    async customerTenantsExistingPost(requestParameters: CustomerTenantsExistingPostRequest, initOverrides?: RequestInit): Promise<CustomerTenantDetailed> {
        const response = await this.customerTenantsExistingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerTenantsGetRaw(requestParameters: CustomerTenantsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<CustomerTenant>>> {
        const queryParameters: any = {};

        if (requestParameters.organizationId !== undefined) {
            queryParameters['OrganizationId'] = requestParameters.organizationId;
        }

        if (requestParameters.publisherId !== undefined) {
            queryParameters['PublisherId'] = requestParameters.publisherId;
        }

        if (requestParameters.programId !== undefined) {
            queryParameters['ProgramId'] = requestParameters.programId;
        }

        if (requestParameters.consumerId !== undefined) {
            queryParameters['ConsumerId'] = requestParameters.consumerId;
        }

        if (requestParameters.domain !== undefined) {
            queryParameters['Domain'] = requestParameters.domain;
        }

        if (requestParameters.domainPrefix !== undefined) {
            queryParameters['DomainPrefix'] = requestParameters.domainPrefix;
        }

        if (requestParameters.customerTenantType !== undefined) {
            queryParameters['CustomerTenantType'] = requestParameters.customerTenantType;
        }

        if (requestParameters.invoiceProfileId !== undefined) {
            queryParameters['InvoiceProfileId'] = requestParameters.invoiceProfileId;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CustomerTenantFromJSON));
    }

    /**
     */
    async customerTenantsGet(requestParameters: CustomerTenantsGetRequest, initOverrides?: RequestInit): Promise<Array<CustomerTenant>> {
        const response = await this.customerTenantsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerTenantsIdDeleteRaw(requestParameters: CustomerTenantsIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customerTenantsIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async customerTenantsIdDelete(requestParameters: CustomerTenantsIdDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.customerTenantsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async customerTenantsIdDetailedGetRaw(requestParameters: CustomerTenantsIdDetailedGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomerTenantDetailed>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customerTenantsIdDetailedGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants/{id}/detailed`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerTenantDetailedFromJSON(jsonValue));
    }

    /**
     */
    async customerTenantsIdDetailedGet(requestParameters: CustomerTenantsIdDetailedGetRequest, initOverrides?: RequestInit): Promise<CustomerTenantDetailed> {
        const response = await this.customerTenantsIdDetailedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerTenantsIdGetRaw(requestParameters: CustomerTenantsIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomerTenant>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customerTenantsIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerTenantFromJSON(jsonValue));
    }

    /**
     */
    async customerTenantsIdGet(requestParameters: CustomerTenantsIdGetRequest, initOverrides?: RequestInit): Promise<CustomerTenant> {
        const response = await this.customerTenantsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerTenantsIdPutRaw(requestParameters: CustomerTenantsIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomerTenantDetailed>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling customerTenantsIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerTenantDetailedToJSON(requestParameters.customerTenantDetailed),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerTenantDetailedFromJSON(jsonValue));
    }

    /**
     */
    async customerTenantsIdPut(requestParameters: CustomerTenantsIdPutRequest, initOverrides?: RequestInit): Promise<CustomerTenantDetailed> {
        const response = await this.customerTenantsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customerTenantsPostRaw(requestParameters: CustomerTenantsPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomerTenantDetailed>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/CustomerTenants`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerTenantDetailedToJSON(requestParameters.customerTenantDetailed),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerTenantDetailedFromJSON(jsonValue));
    }

    /**
     */
    async customerTenantsPost(requestParameters: CustomerTenantsPostRequest, initOverrides?: RequestInit): Promise<CustomerTenantDetailed> {
        const response = await this.customerTenantsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
