/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    FacebookOrder,
    FacebookOrderFromJSON,
    FacebookOrderToJSON,
} from '../models';

export interface FacebookOrdersCheckoutPostRequest {
    facebookOrder?: FacebookOrder;
}

/**
 * 
 */
export class FacebookOrdersApi extends runtime.BaseAPI {

    /**
     */
    async facebookOrdersCheckoutPostRaw(requestParameters: FacebookOrdersCheckoutPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/FacebookOrders/checkout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: FacebookOrderToJSON(requestParameters.facebookOrder),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async facebookOrdersCheckoutPost(requestParameters: FacebookOrdersCheckoutPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.facebookOrdersCheckoutPostRaw(requestParameters, initOverrides);
    }

}
