/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  FacebookOrder,
  FacebookOrderFromJSON,
  FacebookOrderToJSON,
} from '../models';

export interface CheckoutFacebookOrderRequest {
  facebookOrder?: FacebookOrder;
}

/**
 *
 */
export class FacebookOrdersApi extends runtime.BaseAPI {
  /**
   */
  async checkoutFacebookOrderRaw(
    requestParameters: CheckoutFacebookOrderRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json-patch+json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('BearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/FacebookOrders/checkout`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: FacebookOrderToJSON(requestParameters.facebookOrder),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async checkoutFacebookOrder(
    requestParameters: CheckoutFacebookOrderRequest,
    initOverrides?: RequestInit,
  ): Promise<void> {
    await this.checkoutFacebookOrderRaw(requestParameters, initOverrides);
  }
}
