/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GoogleOrder,
    GoogleOrderFromJSON,
    GoogleOrderToJSON,
} from '../models';

export interface ApiV1GoogleOrdersCheckoutPostRequest {
    googleOrder?: GoogleOrder;
}

/**
 * 
 */
export class GoogleOrdersApi extends runtime.BaseAPI {

    /**
     */
    async apiV1GoogleOrdersCheckoutPostRaw(requestParameters: ApiV1GoogleOrdersCheckoutPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/GoogleOrders/checkout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoogleOrderToJSON(requestParameters.googleOrder),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1GoogleOrdersCheckoutPost(requestParameters: ApiV1GoogleOrdersCheckoutPostRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiV1GoogleOrdersCheckoutPostRaw(requestParameters, initOverrides);
    }

}
