/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Grouping,
    GroupingFromJSON,
    GroupingToJSON,
} from '../models';

export interface ApiV1GroupingsGetRequest {
    organizationId?: number;
    includeRemoved?: boolean;
    search?: string | null;
    page?: number;
    pageSize?: number;
}

export interface ApiV1GroupingsIdDeleteRequest {
    id: number;
}

export interface ApiV1GroupingsIdGetRequest {
    id: number;
}

export interface ApiV1GroupingsIdPutRequest {
    id: number;
    grouping?: Grouping;
}

export interface ApiV1GroupingsPostRequest {
    grouping?: Grouping;
}

/**
 * 
 */
export class GroupingsApi extends runtime.BaseAPI {

    /**
     */
    async apiV1GroupingsGetRaw(requestParameters: ApiV1GroupingsGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Grouping>>> {
        const queryParameters: any = {};

        if (requestParameters.organizationId !== undefined) {
            queryParameters['OrganizationId'] = requestParameters.organizationId;
        }

        if (requestParameters.includeRemoved !== undefined) {
            queryParameters['IncludeRemoved'] = requestParameters.includeRemoved;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/Groupings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GroupingFromJSON));
    }

    /**
     */
    async apiV1GroupingsGet(requestParameters: ApiV1GroupingsGetRequest, initOverrides?: RequestInit): Promise<Array<Grouping>> {
        const response = await this.apiV1GroupingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1GroupingsIdDeleteRaw(requestParameters: ApiV1GroupingsIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiV1GroupingsIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/Groupings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1GroupingsIdDelete(requestParameters: ApiV1GroupingsIdDeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this.apiV1GroupingsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1GroupingsIdGetRaw(requestParameters: ApiV1GroupingsIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Grouping>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiV1GroupingsIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/Groupings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupingFromJSON(jsonValue));
    }

    /**
     */
    async apiV1GroupingsIdGet(requestParameters: ApiV1GroupingsIdGetRequest, initOverrides?: RequestInit): Promise<Grouping> {
        const response = await this.apiV1GroupingsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1GroupingsIdPutRaw(requestParameters: ApiV1GroupingsIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Grouping>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiV1GroupingsIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/Groupings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: GroupingToJSON(requestParameters.grouping),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupingFromJSON(jsonValue));
    }

    /**
     */
    async apiV1GroupingsIdPut(requestParameters: ApiV1GroupingsIdPutRequest, initOverrides?: RequestInit): Promise<Grouping> {
        const response = await this.apiV1GroupingsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1GroupingsPostRaw(requestParameters: ApiV1GroupingsPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Grouping>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/v1/Groupings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GroupingToJSON(requestParameters.grouping),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GroupingFromJSON(jsonValue));
    }

    /**
     */
    async apiV1GroupingsPost(requestParameters: ApiV1GroupingsPostRequest, initOverrides?: RequestInit): Promise<Grouping> {
        const response = await this.apiV1GroupingsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
