/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ProductContainer,
    ProductContainerFromJSON,
    ProductContainerToJSON,
    ProductContainerCategory,
    ProductContainerCategoryFromJSON,
    ProductContainerCategoryToJSON,
    ProductContainerType,
    ProductContainerTypeFromJSON,
    ProductContainerTypeToJSON,
    ProductRowPatch,
    ProductRowPatchFromJSON,
    ProductRowPatchToJSON,
} from '../models';

export interface ProductContainersGetRequest {
    organizationId?: number;
    search?: string | null;
    page?: number;
    pageSize?: number;
    activeDraft?: boolean;
    programId?: number;
    year?: number;
    month?: number;
    userId?: string | null;
    sentByUserId?: string | null;
    type?: ProductContainerType;
    category?: ProductContainerCategory;
    from?: Date | null;
    to?: Date | null;
    includeRemoved?: boolean;
    includeSubsidiaries?: boolean;
}

export interface ProductContainersGetorcreateshoppingcartGetRequest {
    organizationId?: number;
}

export interface ProductContainersIdDeleteRequest {
    id: number;
}

export interface ProductContainersIdGetRequest {
    id: number;
}

export interface ProductContainersIdPutRequest {
    id: number;
    requireEulaAnalysis?: boolean | null;
    productContainer?: ProductContainer;
}

export interface ProductContainersProductContainerIdRowProductRowIdPatchRequest {
    productContainerId: number;
    productRowId: number;
    productRowPatch?: ProductRowPatch;
}

export interface ProductContainersReportbymonthPostRequest {
    year?: number;
    month?: number;
    programId?: number;
    organizationId?: number;
    copyLast?: boolean;
}

export interface ProductContainersRowissuesIdGetRequest {
    id: number;
}

/**
 * 
 */
export class ProductContainersApi extends runtime.BaseAPI {

    /**
     */
    async productContainersGetRaw(requestParameters: ProductContainersGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<ProductContainer>>> {
        const queryParameters: any = {};

        if (requestParameters.organizationId !== undefined) {
            queryParameters['OrganizationId'] = requestParameters.organizationId;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        if (requestParameters.activeDraft !== undefined) {
            queryParameters['ActiveDraft'] = requestParameters.activeDraft;
        }

        if (requestParameters.programId !== undefined) {
            queryParameters['ProgramId'] = requestParameters.programId;
        }

        if (requestParameters.year !== undefined) {
            queryParameters['Year'] = requestParameters.year;
        }

        if (requestParameters.month !== undefined) {
            queryParameters['Month'] = requestParameters.month;
        }

        if (requestParameters.userId !== undefined) {
            queryParameters['UserId'] = requestParameters.userId;
        }

        if (requestParameters.sentByUserId !== undefined) {
            queryParameters['SentByUserId'] = requestParameters.sentByUserId;
        }

        if (requestParameters.type !== undefined) {
            queryParameters['Type'] = requestParameters.type;
        }

        if (requestParameters.category !== undefined) {
            queryParameters['Category'] = requestParameters.category;
        }

        if (requestParameters.from !== undefined) {
            queryParameters['From'] = (requestParameters.from as any).toISOString();
        }

        if (requestParameters.to !== undefined) {
            queryParameters['To'] = (requestParameters.to as any).toISOString();
        }

        if (requestParameters.includeRemoved !== undefined) {
            queryParameters['IncludeRemoved'] = requestParameters.includeRemoved;
        }

        if (requestParameters.includeSubsidiaries !== undefined) {
            queryParameters['IncludeSubsidiaries'] = requestParameters.includeSubsidiaries;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductContainerFromJSON));
    }

    /**
     */
    async productContainersGet(requestParameters: ProductContainersGetRequest, initOverrides?: RequestInit): Promise<Array<ProductContainer>> {
        const response = await this.productContainersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productContainersGetorcreateshoppingcartGetRaw(requestParameters: ProductContainersGetorcreateshoppingcartGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ProductContainer>> {
        const queryParameters: any = {};

        if (requestParameters.organizationId !== undefined) {
            queryParameters['organizationId'] = requestParameters.organizationId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers/getorcreateshoppingcart`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductContainerFromJSON(jsonValue));
    }

    /**
     */
    async productContainersGetorcreateshoppingcartGet(requestParameters: ProductContainersGetorcreateshoppingcartGetRequest, initOverrides?: RequestInit): Promise<ProductContainer> {
        const response = await this.productContainersGetorcreateshoppingcartGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productContainersIdDeleteRaw(requestParameters: ProductContainersIdDeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling productContainersIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.TextApiResponse(response) as any;
    }

    /**
     */
    async productContainersIdDelete(requestParameters: ProductContainersIdDeleteRequest, initOverrides?: RequestInit): Promise<boolean> {
        const response = await this.productContainersIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productContainersIdGetRaw(requestParameters: ProductContainersIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ProductContainer>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling productContainersIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductContainerFromJSON(jsonValue));
    }

    /**
     */
    async productContainersIdGet(requestParameters: ProductContainersIdGetRequest, initOverrides?: RequestInit): Promise<ProductContainer> {
        const response = await this.productContainersIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productContainersIdPutRaw(requestParameters: ProductContainersIdPutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ProductContainer>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling productContainersIdPut.');
        }

        const queryParameters: any = {};

        if (requestParameters.requireEulaAnalysis !== undefined) {
            queryParameters['requireEulaAnalysis'] = requestParameters.requireEulaAnalysis;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProductContainerToJSON(requestParameters.productContainer),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductContainerFromJSON(jsonValue));
    }

    /**
     */
    async productContainersIdPut(requestParameters: ProductContainersIdPutRequest, initOverrides?: RequestInit): Promise<ProductContainer> {
        const response = await this.productContainersIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productContainersProductContainerIdRowProductRowIdPatchRaw(requestParameters: ProductContainersProductContainerIdRowProductRowIdPatchRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ProductContainer>> {
        if (requestParameters.productContainerId === null || requestParameters.productContainerId === undefined) {
            throw new runtime.RequiredError('productContainerId','Required parameter requestParameters.productContainerId was null or undefined when calling productContainersProductContainerIdRowProductRowIdPatch.');
        }

        if (requestParameters.productRowId === null || requestParameters.productRowId === undefined) {
            throw new runtime.RequiredError('productRowId','Required parameter requestParameters.productRowId was null or undefined when calling productContainersProductContainerIdRowProductRowIdPatch.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers/{productContainerId}/row/{productRowId}`.replace(`{${"productContainerId"}}`, encodeURIComponent(String(requestParameters.productContainerId))).replace(`{${"productRowId"}}`, encodeURIComponent(String(requestParameters.productRowId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProductRowPatchToJSON(requestParameters.productRowPatch),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductContainerFromJSON(jsonValue));
    }

    /**
     */
    async productContainersProductContainerIdRowProductRowIdPatch(requestParameters: ProductContainersProductContainerIdRowProductRowIdPatchRequest, initOverrides?: RequestInit): Promise<ProductContainer> {
        const response = await this.productContainersProductContainerIdRowProductRowIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productContainersReportbymonthPostRaw(requestParameters: ProductContainersReportbymonthPostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ProductContainer>> {
        const queryParameters: any = {};

        if (requestParameters.year !== undefined) {
            queryParameters['year'] = requestParameters.year;
        }

        if (requestParameters.month !== undefined) {
            queryParameters['month'] = requestParameters.month;
        }

        if (requestParameters.programId !== undefined) {
            queryParameters['programId'] = requestParameters.programId;
        }

        if (requestParameters.organizationId !== undefined) {
            queryParameters['organizationId'] = requestParameters.organizationId;
        }

        if (requestParameters.copyLast !== undefined) {
            queryParameters['copyLast'] = requestParameters.copyLast;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers/reportbymonth`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductContainerFromJSON(jsonValue));
    }

    /**
     */
    async productContainersReportbymonthPost(requestParameters: ProductContainersReportbymonthPostRequest, initOverrides?: RequestInit): Promise<ProductContainer> {
        const response = await this.productContainersReportbymonthPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async productContainersRowissuesIdGetRaw(requestParameters: ProductContainersRowissuesIdGetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ProductContainer>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling productContainersRowissuesIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/ProductContainers/rowissues/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductContainerFromJSON(jsonValue));
    }

    /**
     */
    async productContainersRowissuesIdGet(requestParameters: ProductContainersRowissuesIdGetRequest, initOverrides?: RequestInit): Promise<ProductContainer> {
        const response = await this.productContainersRowissuesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
