/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ChangeTypeEnum,
    ChangeTypeEnumFromJSON,
    ChangeTypeEnumFromJSONTyped,
    ChangeTypeEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface ActivityLogItem
 */
export interface ActivityLogItem {
    /**
     * 
     * @type {string}
     * @memberof ActivityLogItem
     */
    entity?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ActivityLogItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogItem
     */
    changedBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ActivityLogItem
     */
    changedDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogItem
     */
    changedColumn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogItem
     */
    changedFrom?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActivityLogItem
     */
    changedTo?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ActivityLogItem
     */
    customValues?: { [key: string]: string; } | null;
    /**
     * 
     * @type {ChangeTypeEnum}
     * @memberof ActivityLogItem
     */
    changeType?: ChangeTypeEnum;
}

export function ActivityLogItemFromJSON(json: any): ActivityLogItem {
    return ActivityLogItemFromJSONTyped(json, false);
}

export function ActivityLogItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityLogItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entity': !exists(json, 'entity') ? undefined : json['entity'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'changedBy': !exists(json, 'changedBy') ? undefined : json['changedBy'],
        'changedDate': !exists(json, 'changedDate') ? undefined : (new Date(json['changedDate'])),
        'changedColumn': !exists(json, 'changedColumn') ? undefined : json['changedColumn'],
        'changedFrom': !exists(json, 'changedFrom') ? undefined : json['changedFrom'],
        'changedTo': !exists(json, 'changedTo') ? undefined : json['changedTo'],
        'customValues': !exists(json, 'customValues') ? undefined : json['customValues'],
        'changeType': !exists(json, 'changeType') ? undefined : ChangeTypeEnumFromJSON(json['changeType']),
    };
}

export function ActivityLogItemToJSON(value?: ActivityLogItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entity': value.entity,
        'id': value.id,
        'changedBy': value.changedBy,
        'changedDate': value.changedDate === undefined ? undefined : (value.changedDate.toISOString()),
        'changedColumn': value.changedColumn,
        'changedFrom': value.changedFrom,
        'changedTo': value.changedTo,
        'customValues': value.customValues,
        'changeType': ChangeTypeEnumToJSON(value.changeType),
    };
}

