/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AgreementTypeConsent {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}

export function AgreementTypeConsentFromJSON(json: any): AgreementTypeConsent {
    return AgreementTypeConsentFromJSONTyped(json, false);
}

export function AgreementTypeConsentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgreementTypeConsent {
    return json as AgreementTypeConsent;
}

export function AgreementTypeConsentToJSON(value?: AgreementTypeConsent | null): any {
    return value as any;
}

