/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgreementIdentityReferenceDto
 */
export interface AgreementIdentityReferenceDto {
    /**
     * 
     * @type {string}
     * @memberof AgreementIdentityReferenceDto
     */
    agreementNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgreementIdentityReferenceDto
     */
    commitmentLevel?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AgreementIdentityReferenceDto
     */
    isCustomCommitment?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AgreementIdentityReferenceDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AgreementIdentityReferenceDto
     */
    name?: string | null;
}

export function AgreementIdentityReferenceDtoFromJSON(json: any): AgreementIdentityReferenceDto {
    return AgreementIdentityReferenceDtoFromJSONTyped(json, false);
}

export function AgreementIdentityReferenceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgreementIdentityReferenceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agreementNumber': !exists(json, 'agreementNumber') ? undefined : json['agreementNumber'],
        'commitmentLevel': !exists(json, 'commitmentLevel') ? undefined : json['commitmentLevel'],
        'isCustomCommitment': !exists(json, 'isCustomCommitment') ? undefined : json['isCustomCommitment'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function AgreementIdentityReferenceDtoToJSON(value?: AgreementIdentityReferenceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agreementNumber': value.agreementNumber,
        'commitmentLevel': value.commitmentLevel,
        'isCustomCommitment': value.isCustomCommitment,
        'id': value.id,
        'name': value.name,
    };
}

