/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum AssetStatus {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_4 = 4,
  NUMBER_8 = 8,
  NUMBER_15 = 15,
}

export function AssetStatusFromJSON(json: any): AssetStatus {
  return AssetStatusFromJSONTyped(json, false);
}

export function AssetStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssetStatus {
  return json as AssetStatus;
}

export function AssetStatusToJSON(value?: AssetStatus | null): any {
  return value as any;
}
