/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AzureSubscriptionTags,
    AzureSubscriptionTagsFromJSON,
    AzureSubscriptionTagsFromJSONTyped,
    AzureSubscriptionTagsToJSON,
    ObjectReference,
    ObjectReferenceFromJSON,
    ObjectReferenceFromJSONTyped,
    ObjectReferenceToJSON,
} from './';

/**
 * 
 * @export
 * @interface AzureSubscription
 */
export interface AzureSubscription {
    /**
     * 
     * @type {number}
     * @memberof AzureSubscription
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AzureSubscription
     */
    azurePlanId?: number;
    /**
     * 
     * @type {string}
     * @memberof AzureSubscription
     */
    publisherSubscriptionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AzureSubscription
     */
    friendlyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AzureSubscription
     */
    status?: string | null;
    /**
     * 
     * @type {ObjectReference}
     * @memberof AzureSubscription
     */
    invoiceProfile?: ObjectReference;
    /**
     * 
     * @type {AzureSubscriptionTags}
     * @memberof AzureSubscription
     */
    tags?: AzureSubscriptionTags;
}

export function AzureSubscriptionFromJSON(json: any): AzureSubscription {
    return AzureSubscriptionFromJSONTyped(json, false);
}

export function AzureSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AzureSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'azurePlanId': !exists(json, 'azurePlanId') ? undefined : json['azurePlanId'],
        'publisherSubscriptionId': !exists(json, 'publisherSubscriptionId') ? undefined : json['publisherSubscriptionId'],
        'friendlyName': !exists(json, 'friendlyName') ? undefined : json['friendlyName'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'invoiceProfile': !exists(json, 'invoiceProfile') ? undefined : ObjectReferenceFromJSON(json['invoiceProfile']),
        'tags': !exists(json, 'tags') ? undefined : AzureSubscriptionTagsFromJSON(json['tags']),
    };
}

export function AzureSubscriptionToJSON(value?: AzureSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'azurePlanId': value.azurePlanId,
        'publisherSubscriptionId': value.publisherSubscriptionId,
        'friendlyName': value.friendlyName,
        'status': value.status,
        'invoiceProfile': ObjectReferenceToJSON(value.invoiceProfile),
        'tags': AzureSubscriptionTagsToJSON(value.tags),
    };
}

