/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingCycle
 */
export interface BillingCycle {
    /**
     * 
     * @type {number}
     * @memberof BillingCycle
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BillingCycle
     */
    name?: string | null;
}

export function BillingCycleFromJSON(json: any): BillingCycle {
    return BillingCycleFromJSONTyped(json, false);
}

export function BillingCycleFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingCycle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function BillingCycleToJSON(value?: BillingCycle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

