/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingStatementRecordsFile
 */
export interface BillingStatementRecordsFile {
    /**
     * 
     * @type {string}
     * @memberof BillingStatementRecordsFile
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingStatementRecordsFile
     */
    data?: string;
}

export function BillingStatementRecordsFileFromJSON(json: any): BillingStatementRecordsFile {
    return BillingStatementRecordsFileFromJSONTyped(json, false);
}

export function BillingStatementRecordsFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingStatementRecordsFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fileName': !exists(json, 'FileName') ? undefined : json['FileName'],
        'data': !exists(json, 'Data') ? undefined : json['Data'],
    };
}

export function BillingStatementRecordsFileToJSON(value?: BillingStatementRecordsFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'FileName': value.fileName,
        'Data': value.data,
    };
}

