/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ObjectReference,
  ObjectReferenceFromJSON,
  ObjectReferenceFromJSONTyped,
  ObjectReferenceToJSON,
} from './';

/**
 *
 * @export
 * @interface Consumer
 */
export interface Consumer {
  /**
   *
   * @type {number}
   * @memberof Consumer
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof Consumer
   */
  name?: string | null;
  /**
   *
   * @type {ObjectReference}
   * @memberof Consumer
   */
  organization?: ObjectReference;
}

export function ConsumerFromJSON(json: any): Consumer {
  return ConsumerFromJSONTyped(json, false);
}

export function ConsumerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Consumer {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    organization: !exists(json, 'organization')
      ? undefined
      : ObjectReferenceFromJSON(json['organization']),
  };
}

export function ConsumerToJSON(value?: Consumer | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    organization: ObjectReferenceToJSON(value.organization),
  };
}
