/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateAzureSubscriptionRequest
 */
export interface CreateAzureSubscriptionRequest {
  /**
   *
   * @type {string}
   * @memberof CreateAzureSubscriptionRequest
   */
  name?: string | null;
}

export function CreateAzureSubscriptionRequestFromJSON(
  json: any,
): CreateAzureSubscriptionRequest {
  return CreateAzureSubscriptionRequestFromJSONTyped(json, false);
}

export function CreateAzureSubscriptionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAzureSubscriptionRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function CreateAzureSubscriptionRequestToJSON(
  value?: CreateAzureSubscriptionRequest | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
