/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum CustomerTenantType {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
}

export function CustomerTenantTypeFromJSON(json: any): CustomerTenantType {
  return CustomerTenantTypeFromJSONTyped(json, false);
}

export function CustomerTenantTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CustomerTenantType {
  return json as CustomerTenantType;
}

export function CustomerTenantTypeToJSON(
  value?: CustomerTenantType | null,
): any {
  return value as any;
}
