/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum Flow {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_4 = 4,
  NUMBER_9999 = 9999,
}

export function FlowFromJSON(json: any): Flow {
  return FlowFromJSONTyped(json, false);
}

export function FlowFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Flow {
  return json as Flow;
}

export function FlowToJSON(value?: Flow | null): any {
  return value as any;
}
