/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
  /**
   *
   * @type {string}
   * @memberof ModelFile
   */
  fileName?: string;
  /**
   *
   * @type {string}
   * @memberof ModelFile
   */
  data?: string;
}

export function ModelFileFromJSON(json: any): ModelFile {
  return ModelFileFromJSONTyped(json, false);
}

export function ModelFileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelFile {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    fileName: !exists(json, 'fileName') ? undefined : json['fileName'],
    data: !exists(json, 'data') ? undefined : json['data'],
  };
}

export function ModelFileToJSON(value?: ModelFile | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    fileName: value.fileName,
    data: value.data,
  };
}
