/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    crayonCompanyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    accountNumber?: string | null;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'crayonCompanyName': !exists(json, 'crayonCompanyName') ? undefined : json['crayonCompanyName'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
    };
}

export function OrganizationToJSON(value?: Organization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'parentId': value.parentId,
        'crayonCompanyName': value.crayonCompanyName,
        'accountNumber': value.accountNumber,
    };
}

