/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductTypeDto {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}

export function ProductTypeDtoFromJSON(json: any): ProductTypeDto {
    return ProductTypeDtoFromJSONTyped(json, false);
}

export function ProductTypeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTypeDto {
    return json as ProductTypeDto;
}

export function ProductTypeDtoToJSON(value?: ProductTypeDto | null): any {
    return value as any;
}

