/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MinimumCommitmentLight,
    MinimumCommitmentLightFromJSON,
    MinimumCommitmentLightFromJSONTyped,
    MinimumCommitmentLightToJSON,
    ObjectReference,
    ObjectReferenceFromJSON,
    ObjectReferenceFromJSONTyped,
    ObjectReferenceToJSON,
    ProductReference,
    ProductReferenceFromJSON,
    ProductReferenceFromJSONTyped,
    ProductReferenceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductVariant
 */
export interface ProductVariant {
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    id?: number;
    /**
     * 
     * @type {ProductReference}
     * @memberof ProductVariant
     */
    product?: ProductReference;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    partNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    productName?: string | null;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    publisher?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    program?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    productFamily?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    language?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    level?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    productType?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    pool?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    licenseType?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    licenseAgreementType?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    operatingSystem?: ObjectReference;
    /**
     * 
     * @type {ObjectReference}
     * @memberof ProductVariant
     */
    offering?: ObjectReference;
    /**
     * 
     * @type {MinimumCommitmentLight}
     * @memberof ProductVariant
     */
    minimumCommitment?: MinimumCommitmentLight;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    unitCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    purchaseUnit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    purchasePeriod?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariant
     */
    addDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductVariant
     */
    deleteDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    productCategory?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    region?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductVariant
     */
    isTrial?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    defaultBillingCycleId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProductVariant
     */
    availableBillingCycleIds?: Array<number> | null;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof ProductVariant
     */
    attributes?: { [key: string]: object; } | null;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    minimumQuantity?: number;
}

export function ProductVariantFromJSON(json: any): ProductVariant {
    return ProductVariantFromJSONTyped(json, false);
}

export function ProductVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'product': !exists(json, 'product') ? undefined : ProductReferenceFromJSON(json['product']),
        'partNumber': !exists(json, 'partNumber') ? undefined : json['partNumber'],
        'productName': !exists(json, 'productName') ? undefined : json['productName'],
        'publisher': !exists(json, 'publisher') ? undefined : ObjectReferenceFromJSON(json['publisher']),
        'program': !exists(json, 'program') ? undefined : ObjectReferenceFromJSON(json['program']),
        'productFamily': !exists(json, 'productFamily') ? undefined : ObjectReferenceFromJSON(json['productFamily']),
        'language': !exists(json, 'language') ? undefined : ObjectReferenceFromJSON(json['language']),
        'level': !exists(json, 'level') ? undefined : ObjectReferenceFromJSON(json['level']),
        'productType': !exists(json, 'productType') ? undefined : ObjectReferenceFromJSON(json['productType']),
        'pool': !exists(json, 'pool') ? undefined : ObjectReferenceFromJSON(json['pool']),
        'licenseType': !exists(json, 'licenseType') ? undefined : ObjectReferenceFromJSON(json['licenseType']),
        'licenseAgreementType': !exists(json, 'licenseAgreementType') ? undefined : ObjectReferenceFromJSON(json['licenseAgreementType']),
        'operatingSystem': !exists(json, 'operatingSystem') ? undefined : ObjectReferenceFromJSON(json['operatingSystem']),
        'offering': !exists(json, 'offering') ? undefined : ObjectReferenceFromJSON(json['offering']),
        'minimumCommitment': !exists(json, 'minimumCommitment') ? undefined : MinimumCommitmentLightFromJSON(json['minimumCommitment']),
        'unitCount': !exists(json, 'unitCount') ? undefined : json['unitCount'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'purchaseUnit': !exists(json, 'purchaseUnit') ? undefined : json['purchaseUnit'],
        'purchasePeriod': !exists(json, 'purchasePeriod') ? undefined : json['purchasePeriod'],
        'addDate': !exists(json, 'addDate') ? undefined : (new Date(json['addDate'])),
        'deleteDate': !exists(json, 'deleteDate') ? undefined : (new Date(json['deleteDate'])),
        'productCategory': !exists(json, 'productCategory') ? undefined : json['productCategory'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'isTrial': !exists(json, 'isTrial') ? undefined : json['isTrial'],
        'defaultBillingCycleId': !exists(json, 'defaultBillingCycleId') ? undefined : json['defaultBillingCycleId'],
        'availableBillingCycleIds': !exists(json, 'availableBillingCycleIds') ? undefined : json['availableBillingCycleIds'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'minimumQuantity': !exists(json, 'minimumQuantity') ? undefined : json['minimumQuantity'],
    };
}

export function ProductVariantToJSON(value?: ProductVariant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'product': ProductReferenceToJSON(value.product),
        'partNumber': value.partNumber,
        'productName': value.productName,
        'publisher': ObjectReferenceToJSON(value.publisher),
        'program': ObjectReferenceToJSON(value.program),
        'productFamily': ObjectReferenceToJSON(value.productFamily),
        'language': ObjectReferenceToJSON(value.language),
        'level': ObjectReferenceToJSON(value.level),
        'productType': ObjectReferenceToJSON(value.productType),
        'pool': ObjectReferenceToJSON(value.pool),
        'licenseType': ObjectReferenceToJSON(value.licenseType),
        'licenseAgreementType': ObjectReferenceToJSON(value.licenseAgreementType),
        'operatingSystem': ObjectReferenceToJSON(value.operatingSystem),
        'offering': ObjectReferenceToJSON(value.offering),
        'minimumCommitment': MinimumCommitmentLightToJSON(value.minimumCommitment),
        'unitCount': value.unitCount,
        'version': value.version,
        'purchaseUnit': value.purchaseUnit,
        'purchasePeriod': value.purchasePeriod,
        'addDate': value.addDate === undefined ? undefined : (value.addDate.toISOString()),
        'deleteDate': value.deleteDate === undefined ? undefined : (value.deleteDate.toISOString()),
        'productCategory': value.productCategory,
        'region': value.region,
        'isTrial': value.isTrial,
        'defaultBillingCycleId': value.defaultBillingCycleId,
        'availableBillingCycleIds': value.availableBillingCycleIds,
        'attributes': value.attributes,
        'minimumQuantity': value.minimumQuantity,
    };
}

