/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum ProductContainerType {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_4 = 4,
  NUMBER_8 = 8,
  NUMBER_16 = 16,
}

export function ProductContainerTypeFromJSON(json: any): ProductContainerType {
  return ProductContainerTypeFromJSONTyped(json, false);
}

export function ProductContainerTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProductContainerType {
  return json as ProductContainerType;
}

export function ProductContainerTypeToJSON(
  value?: ProductContainerType | null,
): any {
  return value as any;
}
