/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AzureSubscriptionTags,
    AzureSubscriptionTagsFromJSON,
    AzureSubscriptionTagsFromJSONTyped,
    AzureSubscriptionTagsToJSON,
    ObjectReference,
    ObjectReferenceFromJSON,
    ObjectReferenceFromJSONTyped,
    ObjectReferenceToJSON,
} from './';

/**
 * 
 * @export
 * @interface PutAzureSubscription
 */
export interface PutAzureSubscription {
    /**
     * 
     * @type {number}
     * @memberof PutAzureSubscription
     */
    id?: number;
    /**
     * 
     * @type {ObjectReference}
     * @memberof PutAzureSubscription
     */
    invoiceProfile?: ObjectReference;
    /**
     * 
     * @type {AzureSubscriptionTags}
     * @memberof PutAzureSubscription
     */
    tags?: AzureSubscriptionTags;
}

export function PutAzureSubscriptionFromJSON(json: any): PutAzureSubscription {
    return PutAzureSubscriptionFromJSONTyped(json, false);
}

export function PutAzureSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutAzureSubscription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'invoiceProfile': !exists(json, 'invoiceProfile') ? undefined : ObjectReferenceFromJSON(json['invoiceProfile']),
        'tags': !exists(json, 'tags') ? undefined : AzureSubscriptionTagsFromJSON(json['tags']),
    };
}

export function PutAzureSubscriptionToJSON(value?: PutAzureSubscription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'invoiceProfile': ObjectReferenceToJSON(value.invoiceProfile),
        'tags': AzureSubscriptionTagsToJSON(value.tags),
    };
}

