/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ResellerSalesPriceObjectType,
  ResellerSalesPriceObjectTypeFromJSON,
  ResellerSalesPriceObjectTypeFromJSONTyped,
  ResellerSalesPriceObjectTypeToJSON,
} from './';

/**
 *
 * @export
 * @interface ResellerSalesPriceToggle
 */
export interface ResellerSalesPriceToggle {
  /**
   *
   * @type {boolean}
   * @memberof ResellerSalesPriceToggle
   */
  toggle?: boolean;
  /**
   *
   * @type {number}
   * @memberof ResellerSalesPriceToggle
   */
  objectId?: number;
  /**
   *
   * @type {ResellerSalesPriceObjectType}
   * @memberof ResellerSalesPriceToggle
   */
  objectType?: ResellerSalesPriceObjectType;
}

export function ResellerSalesPriceToggleFromJSON(
  json: any,
): ResellerSalesPriceToggle {
  return ResellerSalesPriceToggleFromJSONTyped(json, false);
}

export function ResellerSalesPriceToggleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResellerSalesPriceToggle {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    toggle: !exists(json, 'toggle') ? undefined : json['toggle'],
    objectId: !exists(json, 'objectId') ? undefined : json['objectId'],
    objectType: !exists(json, 'objectType')
      ? undefined
      : ResellerSalesPriceObjectTypeFromJSON(json['objectType']),
  };
}

export function ResellerSalesPriceToggleToJSON(
  value?: ResellerSalesPriceToggle | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    toggle: value.toggle,
    objectId: value.objectId,
    objectType: ResellerSalesPriceObjectTypeToJSON(value.objectType),
  };
}
