/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResellerSalesPriceObjectType,
    ResellerSalesPriceObjectTypeFromJSON,
    ResellerSalesPriceObjectTypeFromJSONTyped,
    ResellerSalesPriceObjectTypeToJSON,
    ResellerSalesPricePriceType,
    ResellerSalesPricePriceTypeFromJSON,
    ResellerSalesPricePriceTypeFromJSONTyped,
    ResellerSalesPricePriceTypeToJSON,
    ResellerSalesPriceType,
    ResellerSalesPriceTypeFromJSON,
    ResellerSalesPriceTypeFromJSONTyped,
    ResellerSalesPriceTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ResellerSalesPrice
 */
export interface ResellerSalesPrice {
    /**
     * 
     * @type {number}
     * @memberof ResellerSalesPrice
     */
    objectId?: number;
    /**
     * 
     * @type {ResellerSalesPriceObjectType}
     * @memberof ResellerSalesPrice
     */
    objectType?: ResellerSalesPriceObjectType;
    /**
     * 
     * @type {ResellerSalesPriceType}
     * @memberof ResellerSalesPrice
     */
    type?: ResellerSalesPriceType;
    /**
     * 
     * @type {ResellerSalesPricePriceType}
     * @memberof ResellerSalesPrice
     */
    priceType?: ResellerSalesPricePriceType;
    /**
     * 
     * @type {number}
     * @memberof ResellerSalesPrice
     */
    value?: number;
    /**
     * 
     * @type {Date}
     * @memberof ResellerSalesPrice
     */
    fromDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ResellerSalesPrice
     */
    changedBy?: string | null;
}

export function ResellerSalesPriceFromJSON(json: any): ResellerSalesPrice {
    return ResellerSalesPriceFromJSONTyped(json, false);
}

export function ResellerSalesPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResellerSalesPrice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectId': !exists(json, 'objectId') ? undefined : json['objectId'],
        'objectType': !exists(json, 'objectType') ? undefined : ResellerSalesPriceObjectTypeFromJSON(json['objectType']),
        'type': !exists(json, 'type') ? undefined : ResellerSalesPriceTypeFromJSON(json['type']),
        'priceType': !exists(json, 'priceType') ? undefined : ResellerSalesPricePriceTypeFromJSON(json['priceType']),
        'value': !exists(json, 'value') ? undefined : json['value'],
        'fromDate': !exists(json, 'fromDate') ? undefined : (new Date(json['fromDate'])),
        'changedBy': !exists(json, 'changedBy') ? undefined : json['changedBy'],
    };
}

export function ResellerSalesPriceToJSON(value?: ResellerSalesPrice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objectId': value.objectId,
        'objectType': ResellerSalesPriceObjectTypeToJSON(value.objectType),
        'type': ResellerSalesPriceTypeToJSON(value.type),
        'priceType': ResellerSalesPricePriceTypeToJSON(value.priceType),
        'value': value.value,
        'fromDate': value.fromDate === undefined ? undefined : (value.fromDate.toISOString()),
        'changedBy': value.changedBy,
    };
}

