/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum SalesPriceType {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_3 = 3,
  NUMBER_null = null,
}

export function SalesPriceTypeFromJSON(json: any): SalesPriceType {
  return SalesPriceTypeFromJSONTyped(json, false);
}

export function SalesPriceTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SalesPriceType {
  return json as SalesPriceType;
}

export function SalesPriceTypeToJSON(value?: SalesPriceType | null): any {
  return value as any;
}
