/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubcategoryUsageCost
 */
export interface SubcategoryUsageCost {
    /**
     * 
     * @type {string}
     * @memberof SubcategoryUsageCost
     */
    meter?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SubcategoryUsageCost
     */
    amount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SubcategoryUsageCost
     */
    currencyCode?: string | null;
}

export function SubcategoryUsageCostFromJSON(json: any): SubcategoryUsageCost {
    return SubcategoryUsageCostFromJSONTyped(json, false);
}

export function SubcategoryUsageCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubcategoryUsageCost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'meter': !exists(json, 'meter') ? undefined : json['meter'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currencyCode': !exists(json, 'currencyCode') ? undefined : json['currencyCode'],
    };
}

export function SubcategoryUsageCostToJSON(value?: SubcategoryUsageCost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'meter': value.meter,
        'amount': value.amount,
        'currencyCode': value.currencyCode,
    };
}

