/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionUsageCostRequest
 */
export interface SubscriptionUsageCostRequest {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUsageCostRequest
     */
    resellerCustomerId?: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUsageCostRequest
     */
    subscriptionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUsageCostRequest
     */
    currencyCode?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionUsageCostRequest
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionUsageCostRequest
     */
    to?: Date;
}

export function SubscriptionUsageCostRequestFromJSON(json: any): SubscriptionUsageCostRequest {
    return SubscriptionUsageCostRequestFromJSONTyped(json, false);
}

export function SubscriptionUsageCostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionUsageCostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resellerCustomerId': !exists(json, 'resellerCustomerId') ? undefined : json['resellerCustomerId'],
        'subscriptionId': !exists(json, 'subscriptionId') ? undefined : json['subscriptionId'],
        'currencyCode': !exists(json, 'currencyCode') ? undefined : json['currencyCode'],
        'from': !exists(json, 'from') ? undefined : (new Date(json['from'])),
        'to': !exists(json, 'to') ? undefined : (new Date(json['to'])),
    };
}

export function SubscriptionUsageCostRequestToJSON(value?: SubscriptionUsageCostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resellerCustomerId': value.resellerCustomerId,
        'subscriptionId': value.subscriptionId,
        'currencyCode': value.currencyCode,
        'from': value.from === undefined ? undefined : (value.from.toISOString()),
        'to': value.to === undefined ? undefined : (value.to.toISOString()),
    };
}

