/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SubscriptionTransitionEligibilityDetail,
    SubscriptionTransitionEligibilityDetailFromJSON,
    SubscriptionTransitionEligibilityDetailFromJSONTyped,
    SubscriptionTransitionEligibilityDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface SubscriptionTransitionEligibility
 */
export interface SubscriptionTransitionEligibility {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionTransitionEligibility
     */
    catalogItemId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionTransitionEligibility
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionTransitionEligibility
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionTransitionEligibility
     */
    quantity?: number;
    /**
     * 
     * @type {Array<SubscriptionTransitionEligibilityDetail>}
     * @memberof SubscriptionTransitionEligibility
     */
    eligibilities?: Array<SubscriptionTransitionEligibilityDetail> | null;
}

export function SubscriptionTransitionEligibilityFromJSON(json: any): SubscriptionTransitionEligibility {
    return SubscriptionTransitionEligibilityFromJSONTyped(json, false);
}

export function SubscriptionTransitionEligibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionTransitionEligibility {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'catalogItemId': !exists(json, 'catalogItemId') ? undefined : json['catalogItemId'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'eligibilities': !exists(json, 'eligibilities') ? undefined : (json['eligibilities'] === null ? null : (json['eligibilities'] as Array<any>).map(SubscriptionTransitionEligibilityDetailFromJSON)),
    };
}

export function SubscriptionTransitionEligibilityToJSON(value?: SubscriptionTransitionEligibility | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'catalogItemId': value.catalogItemId,
        'title': value.title,
        'description': value.description,
        'quantity': value.quantity,
        'eligibilities': value.eligibilities === undefined ? undefined : (value.eligibilities === null ? null : (value.eligibilities as Array<any>).map(SubscriptionTransitionEligibilityDetailToJSON)),
    };
}

