/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionUsageCost
 */
export interface SubscriptionUsageCost {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUsageCost
     */
    category?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionUsageCost
     */
    amount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionUsageCost
     */
    currencyCode?: string | null;
}

export function SubscriptionUsageCostFromJSON(json: any): SubscriptionUsageCost {
    return SubscriptionUsageCostFromJSONTyped(json, false);
}

export function SubscriptionUsageCostFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionUsageCost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'category': !exists(json, 'category') ? undefined : json['category'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currencyCode': !exists(json, 'currencyCode') ? undefined : json['currencyCode'],
    };
}

export function SubscriptionUsageCostToJSON(value?: SubscriptionUsageCost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category': value.category,
        'amount': value.amount,
        'currencyCode': value.currencyCode,
    };
}

