/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  BillingCycleEnum,
  BillingCycleEnumFromJSON,
  BillingCycleEnumFromJSONTyped,
  BillingCycleEnumToJSON,
  CustomerTenantReference,
  CustomerTenantReferenceFromJSON,
  CustomerTenantReferenceFromJSONTyped,
  CustomerTenantReferenceToJSON,
  ObjectReference,
  ObjectReferenceFromJSON,
  ObjectReferenceFromJSONTyped,
  ObjectReferenceToJSON,
  ProductReference,
  ProductReferenceFromJSON,
  ProductReferenceFromJSONTyped,
  ProductReferenceToJSON,
  ProvisionType,
  ProvisionTypeFromJSON,
  ProvisionTypeFromJSONTyped,
  ProvisionTypeToJSON,
  SubscriptionAddOn,
  SubscriptionAddOnFromJSON,
  SubscriptionAddOnFromJSONTyped,
  SubscriptionAddOnToJSON,
  SubscriptionPriceType,
  SubscriptionPriceTypeFromJSON,
  SubscriptionPriceTypeFromJSONTyped,
  SubscriptionPriceTypeToJSON,
  SubscriptionPricing,
  SubscriptionPricingFromJSON,
  SubscriptionPricingFromJSONTyped,
  SubscriptionPricingToJSON,
  SubscriptionStatus,
  SubscriptionStatusFromJSON,
  SubscriptionStatusFromJSONTyped,
  SubscriptionStatusToJSON,
  SubscriptionTags,
  SubscriptionTagsFromJSON,
  SubscriptionTagsFromJSONTyped,
  SubscriptionTagsToJSON,
} from './';

/**
 *
 * @export
 * @interface SubscriptionDetailed
 */
export interface SubscriptionDetailed {
  /**
   *
   * @type {Date}
   * @memberof SubscriptionDetailed
   */
  effectiveStartDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof SubscriptionDetailed
   */
  commitmentEndDate?: Date;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetailed
   */
  suspensionReasons?: string | null;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetailed
   */
  originalAgreementId?: number | null;
  /**
   *
   * @type {SubscriptionPricing}
   * @memberof SubscriptionDetailed
   */
  pricing?: SubscriptionPricing;
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionDetailed
   */
  attestationAccepted?: boolean | null;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetailed
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetailed
   */
  publisherSubscriptionId?: string | null;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetailed
   */
  entitlementId?: string | null;
  /**
   *
   * @type {ObjectReference}
   * @memberof SubscriptionDetailed
   */
  publisher?: ObjectReference;
  /**
   *
   * @type {ObjectReference}
   * @memberof SubscriptionDetailed
   */
  organization?: ObjectReference;
  /**
   *
   * @type {CustomerTenantReference}
   * @memberof SubscriptionDetailed
   */
  customerTenant?: CustomerTenantReference;
  /**
   *
   * @type {ProductReference}
   * @memberof SubscriptionDetailed
   */
  product?: ProductReference;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetailed
   */
  quantity?: number;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetailed
   */
  name?: string | null;
  /**
   *
   * @type {SubscriptionStatus}
   * @memberof SubscriptionDetailed
   */
  status?: SubscriptionStatus;
  /**
   *
   * @type {ProvisionType}
   * @memberof SubscriptionDetailed
   */
  provisionType?: ProvisionType;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetailed
   */
  availableAddonsCount?: number;
  /**
   *
   * @type {Array<SubscriptionAddOn>}
   * @memberof SubscriptionDetailed
   */
  subscriptions?: Array<SubscriptionAddOn> | null;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetailed
   */
  orderId?: string | null;
  /**
   *
   * @type {Date}
   * @memberof SubscriptionDetailed
   */
  creationDate?: Date;
  /**
   *
   * @type {BillingCycleEnum}
   * @memberof SubscriptionDetailed
   */
  billingCycle?: BillingCycleEnum;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetailed
   */
  markup?: number;
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionDetailed
   */
  isTrial?: boolean;
  /**
   *
   * @type {Date}
   * @memberof SubscriptionDetailed
   */
  startDate?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof SubscriptionDetailed
   */
  endDate?: Date | null;
  /**
   *
   * @type {SubscriptionPriceType}
   * @memberof SubscriptionDetailed
   */
  priceType?: SubscriptionPriceType;
  /**
   *
   * @type {number}
   * @memberof SubscriptionDetailed
   */
  salesPrice?: number;
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionDetailed
   */
  registeredForReservedInstance?: boolean;
  /**
   *
   * @type {ObjectReference}
   * @memberof SubscriptionDetailed
   */
  invoiceProfile?: ObjectReference;
  /**
   *
   * @type {SubscriptionTags}
   * @memberof SubscriptionDetailed
   */
  subscriptionTags?: SubscriptionTags;
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionDetailed
   */
  acceptAutoSuspension?: boolean | null;
  /**
   *
   * @type {Date}
   * @memberof SubscriptionDetailed
   */
  autoSuspensionDate?: Date | null;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetailed
   */
  partNumber?: string | null;
  /**
   *
   * @type {string}
   * @memberof SubscriptionDetailed
   */
  termDuration?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof SubscriptionDetailed
   */
  autoRenewEnabled?: boolean | null;
}

export function SubscriptionDetailedFromJSON(json: any): SubscriptionDetailed {
  return SubscriptionDetailedFromJSONTyped(json, false);
}

export function SubscriptionDetailedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubscriptionDetailed {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    effectiveStartDate: !exists(json, 'effectiveStartDate')
      ? undefined
      : new Date(json['effectiveStartDate']),
    commitmentEndDate: !exists(json, 'commitmentEndDate')
      ? undefined
      : new Date(json['commitmentEndDate']),
    suspensionReasons: !exists(json, 'suspensionReasons')
      ? undefined
      : json['suspensionReasons'],
    originalAgreementId: !exists(json, 'originalAgreementId')
      ? undefined
      : json['originalAgreementId'],
    pricing: !exists(json, 'pricing')
      ? undefined
      : SubscriptionPricingFromJSON(json['pricing']),
    attestationAccepted: !exists(json, 'attestationAccepted')
      ? undefined
      : json['attestationAccepted'],
    id: !exists(json, 'id') ? undefined : json['id'],
    publisherSubscriptionId: !exists(json, 'publisherSubscriptionId')
      ? undefined
      : json['publisherSubscriptionId'],
    entitlementId: !exists(json, 'entitlementId')
      ? undefined
      : json['entitlementId'],
    publisher: !exists(json, 'publisher')
      ? undefined
      : ObjectReferenceFromJSON(json['publisher']),
    organization: !exists(json, 'organization')
      ? undefined
      : ObjectReferenceFromJSON(json['organization']),
    customerTenant: !exists(json, 'customerTenant')
      ? undefined
      : CustomerTenantReferenceFromJSON(json['customerTenant']),
    product: !exists(json, 'product')
      ? undefined
      : ProductReferenceFromJSON(json['product']),
    quantity: !exists(json, 'quantity') ? undefined : json['quantity'],
    name: !exists(json, 'name') ? undefined : json['name'],
    status: !exists(json, 'status')
      ? undefined
      : SubscriptionStatusFromJSON(json['status']),
    provisionType: !exists(json, 'provisionType')
      ? undefined
      : ProvisionTypeFromJSON(json['provisionType']),
    availableAddonsCount: !exists(json, 'availableAddonsCount')
      ? undefined
      : json['availableAddonsCount'],
    subscriptions: !exists(json, 'subscriptions')
      ? undefined
      : json['subscriptions'] === null
      ? null
      : (json['subscriptions'] as Array<any>).map(SubscriptionAddOnFromJSON),
    orderId: !exists(json, 'orderId') ? undefined : json['orderId'],
    creationDate: !exists(json, 'creationDate')
      ? undefined
      : new Date(json['creationDate']),
    billingCycle: !exists(json, 'billingCycle')
      ? undefined
      : BillingCycleEnumFromJSON(json['billingCycle']),
    markup: !exists(json, 'markup') ? undefined : json['markup'],
    isTrial: !exists(json, 'isTrial') ? undefined : json['isTrial'],
    startDate: !exists(json, 'startDate')
      ? undefined
      : json['startDate'] === null
      ? null
      : new Date(json['startDate']),
    endDate: !exists(json, 'endDate')
      ? undefined
      : json['endDate'] === null
      ? null
      : new Date(json['endDate']),
    priceType: !exists(json, 'priceType')
      ? undefined
      : SubscriptionPriceTypeFromJSON(json['priceType']),
    salesPrice: !exists(json, 'salesPrice') ? undefined : json['salesPrice'],
    registeredForReservedInstance: !exists(
      json,
      'registeredForReservedInstance',
    )
      ? undefined
      : json['registeredForReservedInstance'],
    invoiceProfile: !exists(json, 'invoiceProfile')
      ? undefined
      : ObjectReferenceFromJSON(json['invoiceProfile']),
    subscriptionTags: !exists(json, 'subscriptionTags')
      ? undefined
      : SubscriptionTagsFromJSON(json['subscriptionTags']),
    acceptAutoSuspension: !exists(json, 'acceptAutoSuspension')
      ? undefined
      : json['acceptAutoSuspension'],
    autoSuspensionDate: !exists(json, 'autoSuspensionDate')
      ? undefined
      : json['autoSuspensionDate'] === null
      ? null
      : new Date(json['autoSuspensionDate']),
    partNumber: !exists(json, 'partNumber') ? undefined : json['partNumber'],
    termDuration: !exists(json, 'termDuration')
      ? undefined
      : json['termDuration'],
    autoRenewEnabled: !exists(json, 'autoRenewEnabled')
      ? undefined
      : json['autoRenewEnabled'],
  };
}

export function SubscriptionDetailedToJSON(
  value?: SubscriptionDetailed | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    effectiveStartDate:
      value.effectiveStartDate === undefined
        ? undefined
        : value.effectiveStartDate.toISOString(),
    commitmentEndDate:
      value.commitmentEndDate === undefined
        ? undefined
        : value.commitmentEndDate.toISOString(),
    suspensionReasons: value.suspensionReasons,
    originalAgreementId: value.originalAgreementId,
    pricing: SubscriptionPricingToJSON(value.pricing),
    attestationAccepted: value.attestationAccepted,
    id: value.id,
    publisherSubscriptionId: value.publisherSubscriptionId,
    entitlementId: value.entitlementId,
    publisher: ObjectReferenceToJSON(value.publisher),
    organization: ObjectReferenceToJSON(value.organization),
    customerTenant: CustomerTenantReferenceToJSON(value.customerTenant),
    product: ProductReferenceToJSON(value.product),
    quantity: value.quantity,
    name: value.name,
    status: SubscriptionStatusToJSON(value.status),
    provisionType: ProvisionTypeToJSON(value.provisionType),
    availableAddonsCount: value.availableAddonsCount,
    subscriptions:
      value.subscriptions === undefined
        ? undefined
        : value.subscriptions === null
        ? null
        : (value.subscriptions as Array<any>).map(SubscriptionAddOnToJSON),
    orderId: value.orderId,
    creationDate:
      value.creationDate === undefined
        ? undefined
        : value.creationDate.toISOString(),
    billingCycle: BillingCycleEnumToJSON(value.billingCycle),
    markup: value.markup,
    isTrial: value.isTrial,
    startDate:
      value.startDate === undefined
        ? undefined
        : value.startDate === null
        ? null
        : value.startDate.toISOString(),
    endDate:
      value.endDate === undefined
        ? undefined
        : value.endDate === null
        ? null
        : value.endDate.toISOString(),
    priceType: SubscriptionPriceTypeToJSON(value.priceType),
    salesPrice: value.salesPrice,
    registeredForReservedInstance: value.registeredForReservedInstance,
    invoiceProfile: ObjectReferenceToJSON(value.invoiceProfile),
    subscriptionTags: SubscriptionTagsToJSON(value.subscriptionTags),
    acceptAutoSuspension: value.acceptAutoSuspension,
    autoSuspensionDate:
      value.autoSuspensionDate === undefined
        ? undefined
        : value.autoSuspensionDate === null
        ? null
        : value.autoSuspensionDate.toISOString(),
    partNumber: value.partNumber,
    termDuration: value.termDuration,
    autoRenewEnabled: value.autoRenewEnabled,
  };
}
