/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubscriptionLite
 */
export interface SubscriptionLite {
  /**
   *
   * @type {number}
   * @memberof SubscriptionLite
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof SubscriptionLite
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof SubscriptionLite
   */
  publisherSubscriptionId?: string | null;
  /**
   *
   * @type {string}
   * @memberof SubscriptionLite
   */
  resellerCustomerName?: string | null;
}

export function SubscriptionLiteFromJSON(json: any): SubscriptionLite {
  return SubscriptionLiteFromJSONTyped(json, false);
}

export function SubscriptionLiteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubscriptionLite {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    publisherSubscriptionId: !exists(json, 'publisherSubscriptionId')
      ? undefined
      : json['publisherSubscriptionId'],
    resellerCustomerName: !exists(json, 'resellerCustomerName')
      ? undefined
      : json['resellerCustomerName'],
  };
}

export function SubscriptionLiteToJSON(value?: SubscriptionLite | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    publisherSubscriptionId: value.publisherSubscriptionId,
    resellerCustomerName: value.resellerCustomerName,
  };
}
