/* tslint:disable */
/* eslint-disable */
/**
 * Crayon Group Customer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum SubscriptionStatus {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_4 = 4,
  NUMBER_8 = 8,
  NUMBER_16 = 16,
  NUMBER_30 = 30,
  NUMBER_31 = 31,
  NUMBER_32 = 32,
  NUMBER_64 = 64,
}

export function SubscriptionStatusFromJSON(json: any): SubscriptionStatus {
  return SubscriptionStatusFromJSONTyped(json, false);
}

export function SubscriptionStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubscriptionStatus {
  return json as SubscriptionStatus;
}

export function SubscriptionStatusToJSON(
  value?: SubscriptionStatus | null,
): any {
  return value as any;
}
