on:
  push:
    paths:
      - "swagger.json"

jobs:
  generate_files:
    name: Generate Swagger-code
    runs-on: ubuntu-latest
    steps:
      - uses: swaggerapi/swagger-codegen-cli
        name: Generate Swagger-code
        run: |
          generate -i swagger.json \
          -l typescript-node --config config.json \
          --template-dir templates/ -o /dist
  # release:
  #   name: Release new package
