on:
  push:
    branches:
      - master
    # paths:
    #   - "swagger.json"

jobs:
  generate_files:
    name: Generate and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: bjerkio/swagger-codegen-action@master
        name: Generate Swagger-code
        with:
          args: generate -i swagger.json -l typescript-node --config config.json --template-dir templates/
      - name: Release package
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
