on:
  push:
    # paths:
    #   - "swagger.json"

jobs:
  generate_files:
    name: Generate Swagger-code
    runs-on: ubuntu-latest
    steps:
      - uses: docker://swaggerapi/swagger-codegen-cli
        name: Generate Swagger-code
        with:
          args: |
            generate -i /github/workspace/swagger.json -l typescript-node --config /github/workspace/config.json --template-dir /github/workspace/templates/ -o /github/workspace/dist
  # release:
  #   name: Release new package
