on:
  push:
    branches:
      - master
    # paths:
    #   - "swagger.json"

jobs:
  generate_files:
    name: Generate Swagger-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: bjerkio/swagger-codegen-action@master
        name: Generate Swagger-code
        with:
          args: generate -i swagger.json -l typescript-node --config config.json --template-dir templates/
  release:
    name: Release new package
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
